RGV\SiteBundle\Entity\Contacto:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        email:
            type: string
            length: 255
        mensaje:
            type: text
        fecha:
            type: datetime
    lifecycleCallbacks: {  }
