RGV\SiteBundle\Entity\Seccion:
    type: entity
    table: rgvsite_seccion
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        slug:
            type: string
            length: '500'
            gedmo:
              slug:
                separator: -
                style: camel
                fields:
                  - nombre
        titulo:
            type: string
            length: 255
        descripcion:
            type: string
            length: '4000'
        activo:
            type: boolean
        contenido:
            type: text
    lifecycleCallbacks: {  }
