parameters:
#    templates_porto.example.class: Templates\PortoBundle\Example

services:
#    templates_porto.example:
#        class: %templates_porto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
