parameters:
#    corporate.example.class: RGV\CorporateBundle\Example

services:
#    corporate.example:
#        class: %corporate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
