parameters:
#    rgv_site.example.class: RGV\SiteBundle\Example

services:
#    rgv_site.example:
#        class: %rgv_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    rgv_site.admin.config:
        class: RGV\SiteBundle\Admin\ConfigAdmin
        arguments: [~, RGV\SiteBundle\Entity\Config, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Config}
