parameters:
#    rgv_site.example.class: RGV\SiteBundle\Example

services:
    rgv_site.admin.seccion:
        class: RGV\SiteBundle\Admin\SeccionAdmin
        arguments: [~, RGV\SiteBundle\Entity\Seccion, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Seccion}
